-- SQLite

-- Consultando a tabela EMPLOYEES com a tabela LOCATIONS

SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;
    
SELECT  E.* FROM EMPLOYEES AS E
    JOIN LOCATIONS AS L ON (E.ID = L.EMPLOYEE_ID)
    GROUP BY E.ID
    HAVING COUNT(*) >= 2;
