-- SQLite

-- Consultando a tabela CUSTOMERS com a tabela LOCATIONS

SELECT * FROM CUSTOMERS;
SELECT * FROM LOCATIONS;

SELECT  C.* FROM CUSTOMERS AS C
    JOIN LOCATIONS AS L ON (C.ID = L.CUSTOMER_ID)
    GROUP BY C.ID
    HAVING COUNT(*) >= 2;
